services:
  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: juca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/migrations:/docker-entrypoint-initdb.d
    command: ['postgres', '-c', 'log_statement=ddl']
  redis:
    image: redis:7.4.0
    restart: on-failure
    ports:
      - '6379:6379'