server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /api
spring:
  application:
    name: juca-monolith
  main:
    banner-mode: off
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    type: redis
springdoc:
  swagger-ui:
    path: /
  use-fqn: true